title: Sohbet
description: >-
  Sınırsız sohbet ve chat dünyasına hoş geldin! Türkiye'nin en ünlü gevezelerini
  bir çatı altında topladık. Eğer söyleyecek bir sözün varsa ve gevezelik
  yapacak yer arıyorsan hemen içeri gir. Sohbet odalarında oyun, eğlence ve
  müzik keyfi seni bekliyor. Gün
template:
  repo: sohbet-template
  name: sohbet
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
